name: Generate Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # каждый день в полночь
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Akruel
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push generated SVG to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PAT_TOKEN }}   # <--- используем твой персональный токен
          branch: output
          force: true
          directory: dist
